- name: Set up local development environment
  hosts: local
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - {role: dirs, tags: ['dirs', 'bootstrap']}
    - {role: git, tags: ['git']}
    - {role: package_manager, tags: ['package_manager', 'bootstrap']}
    - {role: zsh, tags: ['zsh', 'bootstrap']}
    - {role: vim, tags: ['vim']}
    - {role: python, tags: ['python']}
    - {role: node, tags: ['node']}
    - {role: ruby, tags: ['ruby']}
    - {role: hub, tags: ['hub']}
    - {role: zsh-autoenv, tags: ['zsh-autoenv']}
    - {role: rg, tags: ['rg']}
    - {role: exa, tags: ['exa']}
    - {role: bat, tags: ['bat']}
    - {role: macos, tags: ['macos'], when: ansible_os_family == "Darwin"}
    - {role: wpcli, tags: ['wpcli']}
    - {role: repos, tags: ['repos']}
